/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ControlPanel: typeof import('./src/components/map/ControlPanel.vue')['default']
    DeviceCount: typeof import('./src/components/business/DeviceCount/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    EquipmentAlarm: typeof import('./src/components/business/EquipmentAlarm/index.vue')['default']
    FlightSuitableAnalysisPanel: typeof import('./src/components/business/FlightSuitableAnalysisPanel/index.vue')['default']
    HistoryData: typeof import('./src/components/business/HistoryData/index.vue')['default']
    MapContainer: typeof import('./src/components/map/MapContainer.vue')['default']
    MicroscaleWeather: typeof import('./src/components/business/MicroscaleWeather/index.vue')['default']
    MonitoringPoints: typeof import('./src/components/business/MonitoringPoints/index.vue')['default']
    RealTimeWeatherPanel: typeof import('./src/components/business/Real-timeWeatherPanel/index.vue')['default']
    RegionDetail: typeof import('./src/components/business/RegionDetail/index.vue')['default']
    RegionMoniterList: typeof import('./src/components/business/RegionMoniterList/index.vue')['default']
    RiskWarnings: typeof import('./src/components/business/RiskWarnings/index.vue')['default']
    RouteList: typeof import('./src/components/business/RouteList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterRisk: typeof import('./src/components/business/RouterRisk/index.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SurveillanceFootage: typeof import('./src/components/business/SurveillanceFootage/index.vue')['default']
    TimeProgressBar: typeof import('./src/components/map/TimeProgressBar.vue')['default']
    VueMap: typeof import('./src/components/map/VueMap.vue')['default']
    WeatherElementSelector: typeof import('./src/components/business/WeatherElementSelector/index.vue')['default']
    WeatherForecastPanel: typeof import('./src/components/business/WeatherForecastPanel/index.vue')['default']
    WeatherWarnings: typeof import('./src/components/business/WeatherWarnings/index.vue')['default']
    WindProfileChart: typeof import('./src/components/business/WindProfileChart/index.vue')['default']
    WindTrend: typeof import('./src/components/business/WindTrend/index.vue')['default']
  }
}
