/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AircraftAdapt: typeof import('./src/components/business/AircraftAdapt/index.vue')['default']
    ControlPanel: typeof import('./src/components/map/ControlPanel.vue')['default']
    copy: typeof import('./src/components/map/MapContainer copy.vue')['default']
    CoreIndicators: typeof import('./src/components/business/CoreIndicators/index.vue')['default']
    DeviceCount: typeof import('./src/components/business/DeviceCount/index.vue')['default']
    DeviceTrace: typeof import('./src/components/business/DeviceTrace/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    EquipmentAlarm: typeof import('./src/components/business/EquipmentAlarm/index.vue')['default']
    FlightSuitableAnalysisPanel: typeof import('./src/components/business/FlightSuitableAnalysisPanel/index.vue')['default']
    FlightTasks: typeof import('./src/components/business/FlightTasks/index.vue')['default']
    HistoryData: typeof import('./src/components/business/HistoryData/index.vue')['default']
    IndicatorPanel: typeof import('./src/components/map/IndicatorPanel/index.vue')['default']
    LayerControl: typeof import('./src/components/map/LayerControl/index.vue')['default']
    LayerSettings: typeof import('./src/components/cesium/LayerSettings/index.vue')['default']
    MapContainer: typeof import('./src/components/map/MapContainer.vue')['default']
    MicroscaleWeather: typeof import('./src/components/business/MicroscaleWeather/index.vue')['default']
    MonitoringPoints: typeof import('./src/components/business/MonitoringPoints/index.vue')['default']
    RealTimeWeatherPanel: typeof import('./src/components/business/Real-timeWeatherPanel/index.vue')['default']
    RegionDetail: typeof import('./src/components/business/RegionDetail/index.vue')['default']
    RegionMoniterList: typeof import('./src/components/business/RegionMoniterList/index.vue')['default']
    RiskWarnings: typeof import('./src/components/business/RiskWarnings/index.vue')['default']
    RouteList: typeof import('./src/components/business/RouteList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterRisk: typeof import('./src/components/business/RouterRisk/index.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SurveillanceFootage: typeof import('./src/components/business/SurveillanceFootage/index.vue')['default']
    SystemMessage: typeof import('./src/components/business/SystemMessage/index.vue')['default']
    T: typeof import('./src/components/cesium/LayerSettings/t.vue')['default']
    WeatherElementSelector: typeof import('./src/components/business/WeatherElementSelector/index.vue')['default']
    WeatherForecastPanel: typeof import('./src/components/business/WeatherForecastPanel/index.vue')['default']
    WeatherWarnings: typeof import('./src/components/business/WeatherWarnings/index.vue')['default']
    WindLayerControl: typeof import('./src/components/cesium/WindLayerControl/index.vue')['default']
    WindProfileChart: typeof import('./src/components/business/WindProfileChart/index.vue')['default']
    WindTrend: typeof import('./src/components/business/WindTrend/index.vue')['default']
  }
}
